version: '3.8'
services:
    recruit1:
        build:
            context: ./
        restart: always
        ports:
            - '8000:8000'
        networks:
            - rabitt
networks:
    rabitt:
        name: common
        external: true
