version: '3.8'
services:
    recruit1:
        build:
            context: ./
        environment:
            - MULTIPLICATION=1
            - DIVISION=1
            - ADDITION=1
            - SUBTRACTION=1
            - GOROUTINES=5
        restart: always
        networks:
            - yg
networks:
    yg:
        name: common
        external: true
